name: ci
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13, 3.14]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make devenv

      - name: Run tests
        environment:
            PIP_CACHE_DIR: ".pip-cache"
        run: make clean-all test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: make devenv

      - name: Run pre-commit
        uses: https://git.iamthefij.com/iamthefij/pre-commit-action@v3.1.0

  upload:
    runs-on: ubuntu-latest
    needs: test
    if: "${{ github.event_name != 'pull_request' }}"
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Upload to test repo
        env:
          HATCH_INDEX_USER: "__token__"
          HATCH_INDEX_AUTH: "${{ secrets.PYPI_TEST_TOKEN }}"
        run: make upload-test

      - name: Upload to prod repo
        if: "${{ github.ref_type == 'tag' }}"
        env:
          HATCH_INDEX_USER: "__token__"
          HATCH_INDEX_AUTH: "${{ secrets.PYPI_TOKEN }}"
        run: make upload
